apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-dep
  namespace: ping
spec:
  selector:
    matchLabels:
      app: ping-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ping-app
    spec:
      containers:
        - name: ping
          image: ping:v1
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: '8080'
            - name: PONG_HOST
              value: pong-svc.pong
            - name: PONG_PORT
              value: '8080'
            - name: GRPC_PONG_HOST
              value: grpc-pong-svc.grpc-pong
            - name: GRPC_PONG_PORT
              value: '8080'