apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-ing
  namespace: ping
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ping-svc
            port:
              number: 8080