apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
  namespace: pong
spec:
  selector:
    matchLabels:
      app: pong-app
  replicas: 3
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
        - name: pong
          image: pong:v1
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: '8080'
            - name: DB_HOST
              value: 'database-svc.database'
            - name: DB_PORT
              value: '5432'
            - name: DB_USERNAME
              value: 'admin'
            - name: DB_PASSWORD
              value: 'admin'
            - name: DB_NAME
              value: 'grpcconn'
