apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
  namespace: pong
spec:
  selector:
    matchLabels:
      app: pong-app
  replicas: 2
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
        - name: pong
          image: pong:v1
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: '8080'
            - name: TIMEOUT
              value: '10'